server:
  port: 9443
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:weather.p12
    key-store-password: 1234567890
    key-alias: weather
openweather.api:
  uri: https://api.openweathermap.org/data/2.5/weather
  key: 0cb825dd6ce71469a3d5ef68162cb438