server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:localization.p12
    key-store-password: 1234567890
    key-alias: localization
google.api:
  uri: https://maps.googleapis.com/maps/api
  key: AIzaSyC6xS_wy9sFbN0ykRcZ3MMVvoxILLjLXVk